name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Install key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{secrets.SKEPY_PROD_PRIVATE_KEY}}
        known_hosts: 'placeholder'
    - name: Adding Known Host
      run: ssh-keyscan -H ${{secrets.SKEPY_PROD_HOST}} >> ~/.ssh/known_hosts
    - name: Stop Application
      run: ssh ${{secrets.SKEPY_PROD_USER}}@${{secrets.SKEPY_PROD_HOST}} ; ls -la ; ./scripts/stop.sh
    - name: Deploy rsync
      run: rsync -avz ./ ${{secrets.SKEPY_PROD_USER}}@${{secrets.SKEPY_PROD_HOST}}:/home/sui_buyback_bot/buyback_bot_src/
    - name: Start Application
      run: ssh ${{secrets.SKEPY_PROD_USER}}@${{secrets.SKEPY_PROD_HOST}} ; ./scripts/start.sh
      
